Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        authProvider:
          factoryObjectName: Medienreaktor\AuthChain\Security\AuthChainAuthProviderFactory
Medienreaktor:
  AuthChain:
    chain:
      granting:
        class: Medienreaktor\AuthChain\Security\Test2AuthMiddleware
        position: 3000
      denying:
        class: Medienreaktor\AuthChain\Security\TestAuthMiddleware
        position: 2000
